version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "satoshi-watanabe-0001"
    assignees:
      - "satoshi-watanabe-0001"
    commit-message:
      prefix: "deps"
      include: "scope"
