spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  h2:
    console:
      enabled: true

# JWT Configuration (Optional - uncomment if needed)
# jwt:
#   secret: testSecretKey
#   access-token-expiration: 3600000
#   refresh-token-expiration: 86400000

logging:
  level:
    com.ahamo.dummy.demo2: DEBUG
